services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-database
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

    networks:
      - sgu-net
    restart: unless-stopped

  frontend:
    image: client:1.0-sgu
    build:
      context: ./frontend
      args:
        API_HOST: backend
        API_PORT: 8080
        API_BASE: /sgu-api
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    restart: unless-stopped
    depends_on:
      - database

  backend:
    image: server:1.0-sgu
    build:
      context: ./backend
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-database
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database
    restart: unless-stopped

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true